{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "lights-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lights-swing-2.0.jar",
          "url": "lights-swing-2.0.jar",
          "size": 9826,
          "sha512": "17674ffbafc41594ee036dedfab6f32f3ad261f0c90b22d1c7fba3faa1b4bcc03a3266f2e342447484e1dee4c92461a2aeb6a7b7ce23d22f7d9d93a1d8e4e39b",
          "sha256": "d358f83fa8b4eea6e4751f54d15a82ee562b95d7d0aaaa6dda0d02d7eb356ddf",
          "sha1": "7ea56f901629377cea7856a6a20fcb9f2f521473",
          "md5": "938733969f0009e39e489f6cb6c031f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lights-swing-2.0.jar",
          "url": "lights-swing-2.0.jar",
          "size": 9826,
          "sha512": "17674ffbafc41594ee036dedfab6f32f3ad261f0c90b22d1c7fba3faa1b4bcc03a3266f2e342447484e1dee4c92461a2aeb6a7b7ce23d22f7d9d93a1d8e4e39b",
          "sha256": "d358f83fa8b4eea6e4751f54d15a82ee562b95d7d0aaaa6dda0d02d7eb356ddf",
          "sha1": "7ea56f901629377cea7856a6a20fcb9f2f521473",
          "md5": "938733969f0009e39e489f6cb6c031f1"
        }
      ]
    }
  ]
}
