{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "ornaments-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ornaments-swing-2.0.jar",
          "url": "ornaments-swing-2.0.jar",
          "size": 4909,
          "sha512": "08ea7fb08343ed9999b9285b8218582e43ef96e53d4abf37b912b97f3152dce98270b9b5de3de2fc170edd08b3e6904ae6c3c7fba9e5ff857649247f8d132fff",
          "sha256": "5522d000fab4501b4d268ef2d0c0a8cd44f5e561129600008e607fec5a087102",
          "sha1": "3252ee35a098acf853dec2dff912f6541ddddf57",
          "md5": "031b6136a8d9b95a5550b547acfa7017"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ornaments-swing-2.0.jar",
          "url": "ornaments-swing-2.0.jar",
          "size": 4909,
          "sha512": "08ea7fb08343ed9999b9285b8218582e43ef96e53d4abf37b912b97f3152dce98270b9b5de3de2fc170edd08b3e6904ae6c3c7fba9e5ff857649247f8d132fff",
          "sha256": "5522d000fab4501b4d268ef2d0c0a8cd44f5e561129600008e607fec5a087102",
          "sha1": "3252ee35a098acf853dec2dff912f6541ddddf57",
          "md5": "031b6136a8d9b95a5550b547acfa7017"
        }
      ]
    }
  ]
}
