{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "ornaments-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ornaments-swing-2.0.jar",
          "url": "ornaments-swing-2.0.jar",
          "size": 4909,
          "sha512": "1a180073215de6e20964e39d5c39c09b360e43401cb2e5762cface99514fed20f215d53c1d4f366a6b36cad65bc37c7c21a15e8934e438b374c66b2b80718d10",
          "sha256": "88863da52e9321294cdbfac2a67664eb9cdca4b7e26639c16993e76b3e4ae897",
          "sha1": "096f13afe3beb636e109ca0676d5d50293045c78",
          "md5": "a7810dcd8bd20f9da981e22894e4ffd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ornaments-swing-2.0.jar",
          "url": "ornaments-swing-2.0.jar",
          "size": 4909,
          "sha512": "1a180073215de6e20964e39d5c39c09b360e43401cb2e5762cface99514fed20f215d53c1d4f366a6b36cad65bc37c7c21a15e8934e438b374c66b2b80718d10",
          "sha256": "88863da52e9321294cdbfac2a67664eb9cdca4b7e26639c16993e76b3e4ae897",
          "sha1": "096f13afe3beb636e109ca0676d5d50293045c78",
          "md5": "a7810dcd8bd20f9da981e22894e4ffd7"
        }
      ]
    }
  ]
}
