{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "lights-gif",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-gif",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lights-gif-2.0.jar",
          "url": "lights-gif-2.0.jar",
          "size": 7598,
          "sha512": "dcc9092fb7e6d7cf49be511c79d063c7bd42ca1df8b46617fe8d63ccb5f1069d3c5e3a05c9f765700a2a848fbc7eebb4dd06d9a47266c6eb21db8a272eddd46b",
          "sha256": "0041cb097b6e74c76151cbe5d605dc88d95396f554978248ebba85a2493a3f76",
          "sha1": "075e2eb173c5742980eb81467f8f12feca185b43",
          "md5": "4c85dc1494cdeed17a4bf81f281b29ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-gif",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lights-gif-2.0.jar",
          "url": "lights-gif-2.0.jar",
          "size": 7598,
          "sha512": "dcc9092fb7e6d7cf49be511c79d063c7bd42ca1df8b46617fe8d63ccb5f1069d3c5e3a05c9f765700a2a848fbc7eebb4dd06d9a47266c6eb21db8a272eddd46b",
          "sha256": "0041cb097b6e74c76151cbe5d605dc88d95396f554978248ebba85a2493a3f76",
          "sha1": "075e2eb173c5742980eb81467f8f12feca185b43",
          "md5": "4c85dc1494cdeed17a4bf81f281b29ab"
        }
      ]
    }
  ]
}
