{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "tree",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "swing-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "ui-framework": "swing"
      },
      "available-at": {
        "url": "../../tree-swing/2.0/tree-swing-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "tree-swing",
        "version": "2.0"
      }
    },
    {
      "name": "swing-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "ui-framework": "swing"
      },
      "available-at": {
        "url": "../../tree-swing/2.0/tree-swing-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "tree-swing",
        "version": "2.0"
      }
    },
    {
      "name": "gif-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "ui-framework": "gif"
      },
      "available-at": {
        "url": "../../tree-gif/2.0/tree-gif-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "tree-gif",
        "version": "2.0"
      }
    },
    {
      "name": "gif-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "ui-framework": "gif"
      },
      "available-at": {
        "url": "../../tree-gif/2.0/tree-gif-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "tree-gif",
        "version": "2.0"
      }
    },
    {
      "name": "android-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "ui-framework": "android"
      },
      "available-at": {
        "url": "../../tree-swing/2.0/tree-android-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "tree-android",
        "version": "2.0"
      }
    },
    {
      "name": "android-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "ui-framework": "android"
      },
      "available-at": {
        "url": "../../tree-swing/2.0/tree-android-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "tree-android",
        "version": "2.0"
      }
    }
  ]
}
