{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "train-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "train-swing-2.0.jar",
          "url": "train-swing-2.0.jar",
          "size": 3102,
          "sha512": "b18d774b4a7c46f9a204a7bcdf20230cd997cb50472add54b715136ef8a664ad3772ea0d2fbc24a98cf8f66bc53b6e0d438d9f64a216cfd6d8e3c9724308de04",
          "sha256": "547f0f76b74850d52188b8cfa8fd54c60fb52eebf5610701310e2f097d326092",
          "sha1": "07eddff1d4024cf7eb80b0de9073245a0b0e6f5b",
          "md5": "c263f360683d39beabf2241e6f1e617c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "train-swing-2.0.jar",
          "url": "train-swing-2.0.jar",
          "size": 3102,
          "sha512": "b18d774b4a7c46f9a204a7bcdf20230cd997cb50472add54b715136ef8a664ad3772ea0d2fbc24a98cf8f66bc53b6e0d438d9f64a216cfd6d8e3c9724308de04",
          "sha256": "547f0f76b74850d52188b8cfa8fd54c60fb52eebf5610701310e2f097d326092",
          "sha1": "07eddff1d4024cf7eb80b0de9073245a0b0e6f5b",
          "md5": "c263f360683d39beabf2241e6f1e617c"
        }
      ]
    }
  ]
}
