{
  "formatVersion": "0.4",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "train-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.0",
      "buildId": "lsynp5rhcnhxfl2ctepespyfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "train-swing-2.0.jar",
          "url": "train-swing-2.0.jar",
          "size": 3103,
          "sha1": "af32cbdc3a41e8177c10430359c3dc7c8c915a3f",
          "md5": "c69365f7498bb719c562bfc0ded0f03b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.santasoft.xmastree",
          "module": "tree-swing",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "train-swing-2.0.jar",
          "url": "train-swing-2.0.jar",
          "size": 3103,
          "sha1": "af32cbdc3a41e8177c10430359c3dc7c8c915a3f",
          "md5": "c69365f7498bb719c562bfc0ded0f03b"
        }
      ]
    }
  ]
}
