{
  "formatVersion": "0.4",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "ornaments",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.0",
      "buildId": "elqedkdl5nhnpfsdthgz34x5be"
    }
  },
  "variants": [
    {
      "name": "swing-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "ui-framework": "swing"
      },
      "available-at": {
        "url": "../../ornaments-swing/2.0/ornaments-swing-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "ornaments-swing",
        "version": "2.0"
      }
    },
    {
      "name": "swing-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "ui-framework": "swing"
      },
      "available-at": {
        "url": "../../ornaments-swing/2.0/ornaments-swing-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "ornaments-swing",
        "version": "2.0"
      }
    },
    {
      "name": "android-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "ui-framework": "android"
      },
      "available-at": {
        "url": "../../ornaments-swing/2.0/ornaments-android-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "ornaments-android",
        "version": "2.0"
      }
    },
    {
      "name": "android-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "ui-framework": "android"
      },
      "available-at": {
        "url": "../../ornaments-swing/2.0/ornaments-android-2.0.module",
        "group": "com.santasoft.xmastree",
        "module": "ornaments-android",
        "version": "2.0"
      }
    }
  ]
}
