{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "tree-gif",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.santasoft.xmastree",
          "module": "lights",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "ornaments",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "train",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tree-gif-2.0.jar",
          "url": "tree-gif-2.0.jar",
          "size": 10228,
          "sha512": "ff49f013352b7997db2046a8a1959d670ab3a0d3a90681034f8b04a504442a2ed563cf117b52a29621b7de9f77b11218220a2e7c539cdfabb27babbf3294c980",
          "sha256": "3383df10d2f430886bc0b9386836615bd50e866e7de7b62da500e494f6c184a4",
          "sha1": "30b8e146a44e79dbeca80064afe8ad2469f9ae78",
          "md5": "f4b433fce9e3ed4d37fefe1ea77b2610"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.santasoft.xmastree",
          "module": "lights",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "ornaments",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "train",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tree-gif-2.0.jar",
          "url": "tree-gif-2.0.jar",
          "size": 10228,
          "sha512": "ff49f013352b7997db2046a8a1959d670ab3a0d3a90681034f8b04a504442a2ed563cf117b52a29621b7de9f77b11218220a2e7c539cdfabb27babbf3294c980",
          "sha256": "3383df10d2f430886bc0b9386836615bd50e866e7de7b62da500e494f6c184a4",
          "sha1": "30b8e146a44e79dbeca80064afe8ad2469f9ae78",
          "md5": "f4b433fce9e3ed4d37fefe1ea77b2610"
        }
      ]
    }
  ]
}
