{
  "formatVersion": "1.1",
  "component": {
    "group": "com.santasoft.xmastree",
    "module": "tree-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.santasoft.xmastree",
          "module": "lights",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "ornaments",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "train",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tree-swing-2.0.jar",
          "url": "tree-swing-2.0.jar",
          "size": 7846,
          "sha512": "29e4f90121fb9bb49329b184a9189e2d717f61e536b3775bf4adeb6edfa03255e23974a88d975964747ee8b49d40bf93822d25d2a9aa916cec94f6504de890c7",
          "sha256": "8bf825af882bbdbf7ec4e8ac7ab6b2f4f34301a7d09b01b86e071915082f2d72",
          "sha1": "25568e5e97f4e9f8680a6cce775b5c09e6f89252",
          "md5": "d094f4089ccad12e9c1d7e05751622d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.santasoft.xmastree",
          "module": "lights",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "ornaments",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.santasoft.xmastree",
          "module": "train",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tree-swing-2.0.jar",
          "url": "tree-swing-2.0.jar",
          "size": 7846,
          "sha512": "29e4f90121fb9bb49329b184a9189e2d717f61e536b3775bf4adeb6edfa03255e23974a88d975964747ee8b49d40bf93822d25d2a9aa916cec94f6504de890c7",
          "sha256": "8bf825af882bbdbf7ec4e8ac7ab6b2f4f34301a7d09b01b86e071915082f2d72",
          "sha1": "25568e5e97f4e9f8680a6cce775b5c09e6f89252",
          "md5": "d094f4089ccad12e9c1d7e05751622d3"
        }
      ]
    }
  ]
}
